// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/1/28 15:02:10
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/admin/Documents/Workspaces/tres-vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Documents/Workspaces/tres-vue/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Documents/Workspaces/tres-vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Documents/Workspaces/tres-vue/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Documents/Workspaces/tres-vue/plugins/**/*.{js,ts,mjs}","C:/Users/admin/Documents/Workspaces/tres-vue/composables/**/*.{js,ts,mjs}","C:/Users/admin/Documents/Workspaces/tres-vue/utils/**/*.{js,ts,mjs}","C:/Users/admin/Documents/Workspaces/tres-vue/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Documents/Workspaces/tres-vue/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Documents/Workspaces/tres-vue/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Documents/Workspaces/tres-vue/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;